name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # 安装并初始化 @microsoft/clarity
    - name: Install and Initialize Clarity
      run: |
        npm install @microsoft/clarity
        # 假设你的 Clarity 项目 ID 是 'yourProjectId'
        node -e "const Clarity = require('@microsoft/clarity'); Clarity.init('ptjgcuakq4');"
